name: Update README

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"  # Runs every day at midnight

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Fetch Random Quote and Update README
        id: update-readme
        run: |
          # Fetch a random quote
          QUOTE=$(curl -s https://zenquotes.io/api/random | jq -r '.[0].q')
          AUTHOR=$(curl -s https://zenquotes.io/api/random | jq -r '.[0].a')

          # Write to README.md
          echo "# 👋 Hi, I’m Deeraj Thakkilapati" > README.md
          echo "" >> README.md
          echo "![Profile Views](https://komarev.com/ghpvc/?username=Deeraj7&color=blue)" >> README.md
          echo "" >> README.md
          echo "I’m a data engineering enthusiast who loves turning ideas into real-world solutions. Whether it’s building data pipelines or finding innovative ways to make data more accessible, I’m always ready to dive in and create impact." >> README.md
          echo "" >> README.md
          echo "## ✨ Daily Inspiration" >> README.md
          echo "> \"$QUOTE\" - **$AUTHOR**" >> README.md
          echo "" >> README.md
          echo "## 📫 Connect with Me!" >> README.md
          echo "[![Email Badge](https://img.shields.io/badge/Email-thakkilapatideeraj@gmail.com-red?style=flat-square&logo=gmail&logoColor=white)](mailto:thakkilapatideeraj@gmail.com)" >> README.md
          echo "[![LinkedIn Badge](https://img.shields.io/badge/LinkedIn-Connect-blue?style=flat-square&logo=linkedin&logoColor=white)](https://www.linkedin.com/in/deerajthakkilapati/)" >> README.md
          echo "" >> README.md
          echo "🌱 **Animated Inspiration:** 🌱" >> README.md
          echo "<p align=\"center\">" >> README.md
          echo "<img src=\"https://img.shields.io/badge/-Stay%20Positive-brightgreen?style=for-the-badge&labelColor=black\" alt=\"Stay Positive\" style=\"animation: pulse 1s infinite;\">" >> README.md
          echo "</p>" >> README.md

      - name: Commit changes
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const content = fs.readFileSync('README.md', 'utf8');
            const { data: file } = await github.rest.repos.getContent({
              owner: 'Deeraj7',
              repo: 'Deeraj7',
              path: 'README.md',
            });
            await github.rest.repos.createOrUpdateFileContents({
              owner: 'Deeraj7',
              repo: 'Deeraj7',
              path: 'README.md',
              message: 'Update README with daily quote',
              content: Buffer.from(content).toString('base64'),
              sha: file.sha,
              committer: {
                name: 'GitHub Action',
                email: 'action@github.com'
              }
            });
