name: Update README

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"  # Runs every day at midnight

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Fetch Random Quote and Update README
        id: update-readme
        run: |
          # Fetch a random quote
          QUOTE=$(curl -s https://zenquotes.io/api/random | jq -r '.[0].q')
          AUTHOR=$(curl -s https://zenquotes.io/api/random | jq -r '.[0].a')

          # Write to README.md
          echo "<h1 align=\"center\">Welcome to My GitHub Profile! 👋</h1>" > README.md
          echo "" >> README.md
          echo "<div align=\"center\">" >> README.md
          echo "" >> README.md
          echo "[![Typing SVG](https://readme-typing-svg.herokuapp.com?font=Fira+Code&weight=500&color=%234DB6AC&size=28&center=true&vCenter=true&width=600&lines=Hello%2C+I'm+Deeraj+Thakkilapati!;Data+Engineer+%7C+Thinker;Data+Engineer+%7C+Learner;Passionate+About+Data+and+Innovation)](https://github.com/Deeraj7)" >> README.md
          echo "" >> README.md
          echo "---" >> README.md
          echo "" >> README.md
          echo "</div>" >> README.md
          echo "" >> README.md
          echo "<p align=\"center\">" >> README.md
          echo "   <img src=\"https://komarev.com/ghpvc/?username=Deeraj7&color=blue\" alt=\"Profile Views\">" >> README.md
          echo "</p>" >> README.md
          echo "" >> README.md
          echo "<p align=\"center\">I’m a passionate data engineering enthusiast who loves transforming ideas into impactful solutions. I specialize in building efficient data pipelines, discovering insights through data, and developing systems that make information accessible and powerful. Always a <strong>Thinker</strong> and <strong>Learner</strong>, I thrive on solving problems and creating meaningful change through data.</p>" >> README.md
          echo "" >> README.md
          echo "---" >> README.md
          echo "" >> README.md
          echo "## ✨ Daily Inspiration" >> README.md
          echo "<marquee behavior=\"scroll\" direction=\"left\" scrollamount=\"5\">" >> README.md
          echo "   \"$QUOTE\" - **$AUTHOR**" >> README.md
          echo "</marquee>" >> README.md
          echo "" >> README.md
          echo "---" >> README.md
          echo "" >> README.md
          echo "## 📫 Connect with Me!" >> README.md
          echo "<p align=\"center\">" >> README.md
          echo "   <a href=\"mailto:thakkilapatideeraj@gmail.com\">" >> README.md
          echo "      <img src=\"https://img.shields.io/badge/Email-thakkilapatideeraj@gmail.com-red?style=for-the-badge&logo=gmail&logoColor=white\" alt=\"Email\" style=\"display: inline-block; animation: bounce 1.5s infinite;\">" >> README.md
          echo "   </a>" >> README.md
          echo "   <a href=\"https://www.linkedin.com/in/deerajthakkilapati/\">" >> README.md
          echo "      <img src=\"https://img.shields.io/badge/LinkedIn-Connect-blue?style=for-the-badge&logo=linkedin&logoColor=white\" alt=\"LinkedIn\" style=\"display: inline-block; animation: bounce 1.5s infinite;\">" >> README.md
          echo "   </a>" >> README.md
          echo "</p>" >> README.md
          echo "" >> README.md
          echo "---" >> README.md
          echo "" >> README.md
          echo "🌱 **Animated Inspiration:** 🌱" >> README.md
          echo "<p align=\"center\">" >> README.md
          echo "   <img src=\"https://img.shields.io/badge/-Stay%20Positive-brightgreen?style=for-the-badge&labelColor=black\" alt=\"Stay Positive\" style=\"animation: pulse 1.5s infinite;\">" >> README.md
          echo "</p>" >> README.md

      - name: Commit changes
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const content = fs.readFileSync('README.md', 'utf8');
            const { data: file } = await github.rest.repos.getContent({
              owner: 'Deeraj7',
              repo: 'Deeraj7',
              path: 'README.md',
            });
            await github.rest.repos.createOrUpdateFileContents({
              owner: 'Deeraj7',
              repo: 'Deeraj7',
              path: 'README.md',
              message: 'Update README with daily quote and latest intro',
              content: Buffer.from(content).toString('base64'),
              sha: file.sha,
              committer: {
                name: 'GitHub Action',
                email: 'action@github.com'
              }
            });
